services:
  - type: web
    name: telegram-request-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: WEB_APP_DOMAIN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0