import time
import random
import logging
import asyncio
import psycopg2
import psycopg2.extras

from aiogram import Router, F
from aiogram.filters import CommandStart
from aiogram.exceptions import TelegramBadRequest, TelegramNotFound
from aiogram.types import Message, CallbackQuery, InlineKeyboardMarkup, InlineKeyboardButton, BufferedInputFile

from config import bot, DATABASE_URL, DESTINATION_CHANNEL_ID, MAIN_CHANNEL_INVITE_LINK, WEB_APP_DOMAIN
from utils import cleanup_unclicked_request, delete_message_later

user_router = Router()

async def proceed_with_verification(chat_id: int, user_full_name: str, file_hash: str, user_msg_id: int):
    """Handles the ad forwarding and verification message sending."""
    request_key = f"{chat_id}_{file_hash}"
    
    ad_url = "https://example.com"
    fwd_msg_id = None
    
    with psycopg2.connect(DATABASE_URL, sslmode='require') as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cursor:
            max_ad_attempts = 5
            for _ in range(max_ad_attempts):
                cursor.execute("DELETE FROM ads WHERE %s - timestamp > 86400", (time.time(),))
                cursor.execute("SELECT channel_id, message_id, url FROM ads")
                ads_db = cursor.fetchall()
                if not ads_db: break

                selected_ad = random.choice(ads_db)
                ad_url, ad_msg_id, ad_channel_id = selected_ad['url'], selected_ad['message_id'], selected_ad['channel_id']

                try:
                    sent_fwd = await bot.forward_message(chat_id=chat_id, from_chat_id=ad_channel_id, message_id=ad_msg_id)
                    fwd_msg_id = sent_fwd.message_id
                    break
                except (TelegramBadRequest, TelegramNotFound) as e:
                    logging.warning(f"Ad message {ad_msg_id} not found. Removing from DB. Error: {e}")
                    cursor.execute("DELETE FROM ads WHERE channel_id = %s AND message_id = %s", (ad_channel_id, ad_msg_id))
                    conn.commit()
            
            cursor.execute("""
                INSERT INTO users (user_id, name, total_requests) VALUES (%s, %s, 1) 
                ON CONFLICT(user_id) DO UPDATE SET total_requests = users.total_requests + 1, name = EXCLUDED.name
            """, (chat_id, user_full_name))
            
    track_url = f"{WEB_APP_DOMAIN}/track?u={chat_id}&h={file_hash}"
    keyboard = InlineKeyboardMarkup(inline_keyboard=[
        [InlineKeyboardButton(text="1️⃣ Click Ad to Verify 👀", url=track_url)],
        [InlineKeyboardButton(text="2️⃣ Get Subtitle File 📥", callback_data=f"get_{file_hash}")]
    ])

    text = ("<b>Verification Required!</b>\n\nPlease click 'Click Ad to Verify' below. 👇\n"
            "After verifying, click 'Get Subtitle File' to receive your file. ✨")
    if not fwd_msg_id:
        text = (f"<b>Verification Required!</b>\n\nPlease click the verification button below. 👇\n\n"
                f"<i>(No specific ad available, but verification is still needed.)</i>")

    bot_reply_msg = await bot.send_message(chat_id, text, reply_markup=keyboard)
    
    with psycopg2.connect(DATABASE_URL, sslmode='require') as conn:
        with conn.cursor() as cursor:
            cursor.execute("""
                INSERT INTO requests (request_key, verified, timestamp, target_url, user_msg_id, bot_fwd_msg_id, bot_reply_msg_id) 
                VALUES (%s, 0, %s, %s, %s, %s, %s)
                ON CONFLICT(request_key) DO UPDATE SET verified = 0, timestamp = EXCLUDED.timestamp, target_url = EXCLUDED.target_url, user_msg_id = EXCLUDED.user_msg_id, bot_fwd_msg_id = EXCLUDED.bot_fwd_msg_id, bot_reply_msg_id = EXCLUDED.bot_reply_msg_id
            """, (request_key, time.time(), ad_url, user_msg_id, fwd_msg_id, bot_reply_msg.message_id))
    
    asyncio.create_task(cleanup_unclicked_request(request_key, chat_id, delay=300))

async def handle_post_deep_link(message: Message, raw_args: str):
    """Handles the deep link generated by the /post command."""
    parts = raw_args.split("_")
    if len(parts) < 3:
        msg = await message.answer("❌ Invalid post link.")
        asyncio.create_task(delete_message_later(msg.chat.id, msg.message_id, 300))
        return
    
    message_id = parts[-1]
    username = "_".join(parts[1:-1])
    user_id = message.from_user.id
    link = f"https://t.me/{username}/{message_id}"

    with psycopg2.connect(DATABASE_URL, sslmode='require') as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cursor:
            # Check user's last verification timestamp
            cursor.execute("SELECT last_verified_timestamp FROM users WHERE user_id = %s", (user_id,))
            user_row = cursor.fetchone()
            
            # If user verified in the last 10 minutes (600 seconds), give link directly
            if user_row and user_row['last_verified_timestamp'] and (time.time() - user_row['last_verified_timestamp'] < 600):
                keyboard = InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="⬇️ Download Episode", url=link)]])
                msg = await message.answer("You are already verified. Here is your episode:", reply_markup=keyboard)
                asyncio.create_task(delete_message_later(msg.chat.id, msg.message_id, 300))
                return

            # --- Proceed with new verification ---
            cursor.execute("SELECT short_name, channel_id, full_name FROM channels")
            all_channels = cursor.fetchall()
    
    if not all_channels:
        keyboard = InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="⬇️ Download Episode", url=link)]])
        msg = await message.answer("Here is your requested episode:", reply_markup=keyboard)
        asyncio.create_task(delete_message_later(msg.chat.id, msg.message_id, 300))
        return
        
    # Select one random channel
    target_channel = random.choice(all_channels)
    req_short_name = target_channel['short_name']
    req_channel_id = target_channel['channel_id']
    channel_full_name = target_channel['full_name']
    
    try:
        member = await bot.get_chat_member(req_channel_id, user_id)
        # If user is already a member of the randomly selected channel, verify them and give the link
        if member.status not in ['left', 'kicked', 'restricted']:
            with psycopg2.connect(DATABASE_URL, sslmode='require') as conn:
                with conn.cursor() as cursor:
                    cursor.execute("INSERT INTO users (user_id, last_verified_timestamp) VALUES (%s, %s) ON CONFLICT(user_id) DO UPDATE SET last_verified_timestamp = EXCLUDED.last_verified_timestamp", (user_id, time.time()))
            keyboard = InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="⬇️ Download Episode", url=link)]])
            msg = await message.answer("Thank you for being a member! Here is your episode:", reply_markup=keyboard)
            asyncio.create_task(delete_message_later(msg.chat.id, msg.message_id, 300))
            return

        # User is NOT a member, so show the join prompt
        chat = await bot.get_chat(req_channel_id)
        invite_link = chat.invite_link
        if not invite_link:
            try: invite_link = await bot.export_chat_invite_link(req_channel_id)
            except Exception as e_link:
                logging.warning(f"Failed to export invite link for {req_channel_id}: {e_link}")
                invite_link = f"https://t.me/{chat.username}" if chat.username else None
        
        callback_data = f"cp_check_{req_short_name}_{username}_{message_id}"
        
        keyboard = InlineKeyboardMarkup(inline_keyboard=[
            [InlineKeyboardButton(text=f"1. Join {channel_full_name} 🚀", url=invite_link)],
            [InlineKeyboardButton(text="2. Download Episode ⬇️", callback_data=callback_data)]
        ])
        msg = await message.answer("<b>Join Required!</b>\n\nPlease join the following channel to get your episode link. 👇", reply_markup=keyboard)
        asyncio.create_task(delete_message_later(msg.chat.id, msg.message_id, 300))

    except Exception as e:
        logging.error(f"Error checking membership for channel {req_channel_id}: {e}")
        msg = await message.answer("❌ <b>System Error:</b> Could not verify channel membership. Please make sure the bot is added as an administrator to all registered force-join channels.")
        asyncio.create_task(delete_message_later(msg.chat.id, msg.message_id, 300))
        return

@user_router.message(CommandStart())
async def handle_start(message: Message, command: CommandStart):
    """Handles the user clicking the deep link."""
    raw_args = command.args
    if not raw_args:
        msg = await message.answer(
            "👋 <b>Welcome!</b>\n\nTo get a file, use a special link from one of our channels."
        )
        asyncio.create_task(delete_message_later(msg.chat.id, msg.message_id, 300))
        return

    if raw_args.startswith("post_"):
        return await handle_post_deep_link(message, raw_args)

    file_hash = raw_args
    user_id = message.from_user.id
    with psycopg2.connect(DATABASE_URL, sslmode='require') as conn:
        with conn.cursor() as cursor:
            cursor.execute("SELECT file_id FROM files WHERE hash = %s", (file_hash,))
            if not cursor.fetchone():
                msg = await message.answer("This file link is invalid or has expired.")
                asyncio.create_task(delete_message_later(msg.chat.id, msg.message_id, 300))
                return

    if DESTINATION_CHANNEL_ID:
        try:
            member = await bot.get_chat_member(DESTINATION_CHANNEL_ID, user_id)
            if member.status in ['left', 'kicked']:
                chat = await bot.get_chat(DESTINATION_CHANNEL_ID)
                invite_link = chat.invite_link or MAIN_CHANNEL_INVITE_LINK
                if invite_link:
                    keyboard = InlineKeyboardMarkup(inline_keyboard=[
                        [InlineKeyboardButton(text=f"1. Join {chat.title} 🚀", url=invite_link)],
                        [InlineKeyboardButton(text="2. ✅ I Have Joined", callback_data=f"verify_join_{file_hash}")]
                    ])
                    msg = await message.answer("<b>Join Required!</b>\n\nTo get your file, you must first join our channel. 👇", reply_markup=keyboard)
                    asyncio.create_task(delete_message_later(msg.chat.id, msg.message_id, 300))
                    return
        except Exception as e:
            logging.error(f"Could not check channel membership for {user_id}: {e}")

    await proceed_with_verification(user_id, message.from_user.full_name, file_hash, message.message_id)

@user_router.callback_query(F.data.startswith("get_"))
async def serve_file(callback: CallbackQuery):
    """Verifies the ad click and serves the file if valid."""
    user_id = callback.from_user.id
    file_hash = callback.data.split("_")[1]
    request_key = f"{user_id}_{file_hash}"
    
    with psycopg2.connect(DATABASE_URL, sslmode='require') as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cursor:
            cursor.execute("SELECT verified, timestamp, user_msg_id, bot_fwd_msg_id FROM requests WHERE request_key = %s", (request_key,))
            req = cursor.fetchone()
            
            if not req:
                return await callback.answer("Invalid or expired session. Please click the original link again.", show_alert=True)
            if time.time() - req['timestamp'] > 300:
                cursor.execute("DELETE FROM requests WHERE request_key = %s", (request_key,))
                return await callback.answer("Request expired (5 mins). Please generate a new one.", show_alert=True)
            if not req['verified']:
                return await callback.answer("❌ You must click 'Click Ad to Verify' first!", show_alert=True)

            cursor.execute("SELECT file_id, filename FROM files WHERE hash = %s", (file_hash,))
            file_row = cursor.fetchone()
            if file_row:
                cursor.execute("UPDATE users SET successful_receives = successful_receives + 1 WHERE user_id = %s", (user_id,))
                cursor.execute("""
                    INSERT INTO user_file_requests (user_id, file_hash, count) VALUES (%s, %s, 1)
                    ON CONFLICT(user_id, file_hash) DO UPDATE SET count = user_file_requests.count + 1
                """, (user_id, file_hash))
                
            cursor.execute("DELETE FROM requests WHERE request_key = %s", (request_key,))
            
    if file_row:
        caption = "✅ Here is your file! 🎉\n\n⏳ <i>This file will be deleted in 5 minutes.</i>"
        sent_file = None
        try:
            file_info = await bot.get_file(file_row['file_id'])
            file_content = await bot.download_file(file_info.file_path)
            document_to_send = BufferedInputFile(file_content.read(), filename=file_row['filename'] or "subtitle.ass")
            sent_file = await bot.send_document(user_id, document_to_send, caption=caption)
        except Exception as e:
            logging.error(f"Failed to re-upload file. Falling back. Error: {e}")
            sent_file = await bot.send_document(user_id, file_row['file_id'], caption=caption)

        for m_id in {callback.message.message_id, req.get('user_msg_id'), req.get('bot_fwd_msg_id')}:
            if m_id:
                try: await bot.delete_message(user_id, m_id)
                except (TelegramNotFound, TelegramBadRequest): pass
                
        if sent_file:
            asyncio.create_task(delete_message_later(user_id, sent_file.message_id, 300))
    else:
        await callback.answer("File no longer available. 😔", show_alert=True)
        
    await callback.answer()

@user_router.callback_query(F.data.startswith("verify_join_"))
async def handle_join_verification(callback: CallbackQuery):
    """Handles the 'I have joined' button click."""
    file_hash = callback.data.split("_")[2]
    user_id = callback.from_user.id

    if not DESTINATION_CHANNEL_ID:
        await callback.answer("This check is no longer required.", show_alert=True)
        return await callback.message.delete()

    try:
        member = await bot.get_chat_member(DESTINATION_CHANNEL_ID, user_id)
        if member.status not in ['left', 'kicked']:
            await callback.answer("Thank you for joining! Please wait... 🙏", show_alert=False)
            await callback.message.delete()
            await proceed_with_verification(user_id, callback.from_user.full_name, file_hash, 0)
        else:
            await callback.answer("❌ You haven't joined the channel yet. Please join and click again.", show_alert=True)
    except Exception as e:
        logging.error(f"Error during join verification for {user_id}: {e}")
        await callback.answer("An error occurred while verifying. Please try again.", show_alert=True)

@user_router.callback_query(F.data.startswith("cp_"))
async def handle_post_join_check(callback: CallbackQuery):
    """Handles the 'Download Episode' button click, verifying the single required channel join."""
    parts = callback.data.split("_")
    if len(parts) < 5 or parts[1] != 'check':
        return await callback.answer("Invalid callback data.", show_alert=True)

    req_short_name = parts[2]
    message_id = parts[-1]
    username = "_".join(parts[3:-1])
    user_id = callback.from_user.id

    with psycopg2.connect(DATABASE_URL, sslmode='require') as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cursor:
            cursor.execute("SELECT channel_id FROM channels WHERE short_name = %s", (req_short_name,))
            channel_row = cursor.fetchone()

    if not channel_row:
        return await callback.answer("The required channel is no longer registered.", show_alert=True)

    req_channel_id = channel_row['channel_id']
    
    try:
        member = await bot.get_chat_member(req_channel_id, user_id)
        if member.status in ['left', 'kicked', 'restricted']:
            return await callback.answer("❌ You haven't joined the required channel yet. Please join and try again.", show_alert=True)
    except Exception:
        return await callback.answer("❌ Configuration Error: The bot must be an admin in the channel to verify membership.", show_alert=True)

    # If check passes, update timestamp and give link
    with psycopg2.connect(DATABASE_URL, sslmode='require') as conn:
        with conn.cursor() as cursor:
            cursor.execute("INSERT INTO users (user_id, last_verified_timestamp) VALUES (%s, %s) ON CONFLICT(user_id) DO UPDATE SET last_verified_timestamp = EXCLUDED.last_verified_timestamp", (user_id, time.time()))

    try:
        await callback.answer("Thank you for joining!", show_alert=False)
        link = f"https://t.me/{username}/{message_id}"
        keyboard = InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="⬇️ Download Episode", url=link)]])
        await callback.message.edit_text("✅ Verification successful! Here is your episode:", reply_markup=keyboard)
        asyncio.create_task(delete_message_later(callback.message.chat.id, callback.message.message_id, 300))
    except Exception as e:
        logging.error(f"Error in final step of handle_post_join_check: {e}")
        await callback.answer("An error occurred. Please try again.", show_alert=True)